//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 CCompiler.g 2015-10-05 01:45:11

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class CCompilerLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__52=52;
	public const int T__53=53;
	public const int T__54=54;
	public const int T__55=55;
	public const int T__56=56;
	public const int T__57=57;
	public const int T__58=58;
	public const int ADD=4;
	public const int AND=5;
	public const int ARGS=6;
	public const int ARGS_DECL=7;
	public const int ASSIGN=8;
	public const int BIT_AND=9;
	public const int BIT_OR=10;
	public const int BLOCK=11;
	public const int CALL=12;
	public const int COMMA=13;
	public const int DIGIT=14;
	public const int DIV=15;
	public const int DO=16;
	public const int ELSE=17;
	public const int EQ=18;
	public const int EscapeSequence=19;
	public const int FALSE=20;
	public const int FOR=21;
	public const int FUNC_DECL=22;
	public const int GE=23;
	public const int GT=24;
	public const int IDENT=25;
	public const int IF=26;
	public const int INCLUDE=27;
	public const int INCLUDE_STRING=28;
	public const int INDEX=29;
	public const int LE=30;
	public const int LETTER=31;
	public const int LINE_COMMENT=32;
	public const int LT=33;
	public const int ML_COMMENT=34;
	public const int MUL=35;
	public const int NE=36;
	public const int NOT=37;
	public const int NUMBER=38;
	public const int OR=39;
	public const int OctalEscape=40;
	public const int PROGRAM=41;
	public const int RETURN=42;
	public const int SEMI=43;
	public const int STRING=44;
	public const int SUB=45;
	public const int TRUE=46;
	public const int TYPE=47;
	public const int UNKNOWN=48;
	public const int VAR=49;
	public const int WHILE=50;
	public const int WS=51;

    // delegates
    // delegators

	public CCompilerLexer()
	{
		OnCreated();
	}

	public CCompilerLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public CCompilerLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "CCompiler.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_AND();
	partial void LeaveRule_AND();

	// $ANTLR start "AND"
	[GrammarRule("AND")]
	private void mAND()
	{
		EnterRule_AND();
		EnterRule("AND", 1);
		TraceIn("AND", 1);
		try
		{
			int _type = AND;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:7:5: ( '&&' )
			DebugEnterAlt(1);
			// CCompiler.g:7:7: '&&'
			{
			DebugLocation(7, 7);
			Match("&&"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("AND", 1);
			LeaveRule("AND", 1);
			LeaveRule_AND();
		}
	}
	// $ANTLR end "AND"

	partial void EnterRule_DO();
	partial void LeaveRule_DO();

	// $ANTLR start "DO"
	[GrammarRule("DO")]
	private void mDO()
	{
		EnterRule_DO();
		EnterRule("DO", 2);
		TraceIn("DO", 2);
		try
		{
			int _type = DO;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:8:4: ( 'do' )
			DebugEnterAlt(1);
			// CCompiler.g:8:6: 'do'
			{
			DebugLocation(8, 6);
			Match("do"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DO", 2);
			LeaveRule("DO", 2);
			LeaveRule_DO();
		}
	}
	// $ANTLR end "DO"

	partial void EnterRule_ELSE();
	partial void LeaveRule_ELSE();

	// $ANTLR start "ELSE"
	[GrammarRule("ELSE")]
	private void mELSE()
	{
		EnterRule_ELSE();
		EnterRule("ELSE", 3);
		TraceIn("ELSE", 3);
		try
		{
			int _type = ELSE;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:9:6: ( 'else' )
			DebugEnterAlt(1);
			// CCompiler.g:9:8: 'else'
			{
			DebugLocation(9, 8);
			Match("else"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ELSE", 3);
			LeaveRule("ELSE", 3);
			LeaveRule_ELSE();
		}
	}
	// $ANTLR end "ELSE"

	partial void EnterRule_FALSE();
	partial void LeaveRule_FALSE();

	// $ANTLR start "FALSE"
	[GrammarRule("FALSE")]
	private void mFALSE()
	{
		EnterRule_FALSE();
		EnterRule("FALSE", 4);
		TraceIn("FALSE", 4);
		try
		{
			int _type = FALSE;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:10:7: ( 'false' )
			DebugEnterAlt(1);
			// CCompiler.g:10:9: 'false'
			{
			DebugLocation(10, 9);
			Match("false"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FALSE", 4);
			LeaveRule("FALSE", 4);
			LeaveRule_FALSE();
		}
	}
	// $ANTLR end "FALSE"

	partial void EnterRule_FOR();
	partial void LeaveRule_FOR();

	// $ANTLR start "FOR"
	[GrammarRule("FOR")]
	private void mFOR()
	{
		EnterRule_FOR();
		EnterRule("FOR", 5);
		TraceIn("FOR", 5);
		try
		{
			int _type = FOR;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:11:5: ( 'for' )
			DebugEnterAlt(1);
			// CCompiler.g:11:7: 'for'
			{
			DebugLocation(11, 7);
			Match("for"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FOR", 5);
			LeaveRule("FOR", 5);
			LeaveRule_FOR();
		}
	}
	// $ANTLR end "FOR"

	partial void EnterRule_IF();
	partial void LeaveRule_IF();

	// $ANTLR start "IF"
	[GrammarRule("IF")]
	private void mIF()
	{
		EnterRule_IF();
		EnterRule("IF", 6);
		TraceIn("IF", 6);
		try
		{
			int _type = IF;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:12:4: ( 'if' )
			DebugEnterAlt(1);
			// CCompiler.g:12:6: 'if'
			{
			DebugLocation(12, 6);
			Match("if"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("IF", 6);
			LeaveRule("IF", 6);
			LeaveRule_IF();
		}
	}
	// $ANTLR end "IF"

	partial void EnterRule_OR();
	partial void LeaveRule_OR();

	// $ANTLR start "OR"
	[GrammarRule("OR")]
	private void mOR()
	{
		EnterRule_OR();
		EnterRule("OR", 7);
		TraceIn("OR", 7);
		try
		{
			int _type = OR;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:13:4: ( '||' )
			DebugEnterAlt(1);
			// CCompiler.g:13:6: '||'
			{
			DebugLocation(13, 6);
			Match("||"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OR", 7);
			LeaveRule("OR", 7);
			LeaveRule_OR();
		}
	}
	// $ANTLR end "OR"

	partial void EnterRule_RETURN();
	partial void LeaveRule_RETURN();

	// $ANTLR start "RETURN"
	[GrammarRule("RETURN")]
	private void mRETURN()
	{
		EnterRule_RETURN();
		EnterRule("RETURN", 8);
		TraceIn("RETURN", 8);
		try
		{
			int _type = RETURN;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:14:8: ( 'return' )
			DebugEnterAlt(1);
			// CCompiler.g:14:10: 'return'
			{
			DebugLocation(14, 10);
			Match("return"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RETURN", 8);
			LeaveRule("RETURN", 8);
			LeaveRule_RETURN();
		}
	}
	// $ANTLR end "RETURN"

	partial void EnterRule_TRUE();
	partial void LeaveRule_TRUE();

	// $ANTLR start "TRUE"
	[GrammarRule("TRUE")]
	private void mTRUE()
	{
		EnterRule_TRUE();
		EnterRule("TRUE", 9);
		TraceIn("TRUE", 9);
		try
		{
			int _type = TRUE;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:15:6: ( 'true' )
			DebugEnterAlt(1);
			// CCompiler.g:15:8: 'true'
			{
			DebugLocation(15, 8);
			Match("true"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("TRUE", 9);
			LeaveRule("TRUE", 9);
			LeaveRule_TRUE();
		}
	}
	// $ANTLR end "TRUE"

	partial void EnterRule_VAR();
	partial void LeaveRule_VAR();

	// $ANTLR start "VAR"
	[GrammarRule("VAR")]
	private void mVAR()
	{
		EnterRule_VAR();
		EnterRule("VAR", 10);
		TraceIn("VAR", 10);
		try
		{
			int _type = VAR;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:16:5: ( 'var' )
			DebugEnterAlt(1);
			// CCompiler.g:16:7: 'var'
			{
			DebugLocation(16, 7);
			Match("var"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("VAR", 10);
			LeaveRule("VAR", 10);
			LeaveRule_VAR();
		}
	}
	// $ANTLR end "VAR"

	partial void EnterRule_WHILE();
	partial void LeaveRule_WHILE();

	// $ANTLR start "WHILE"
	[GrammarRule("WHILE")]
	private void mWHILE()
	{
		EnterRule_WHILE();
		EnterRule("WHILE", 11);
		TraceIn("WHILE", 11);
		try
		{
			int _type = WHILE;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:17:7: ( 'while' )
			DebugEnterAlt(1);
			// CCompiler.g:17:9: 'while'
			{
			DebugLocation(17, 9);
			Match("while"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WHILE", 11);
			LeaveRule("WHILE", 11);
			LeaveRule_WHILE();
		}
	}
	// $ANTLR end "WHILE"

	partial void EnterRule_T__52();
	partial void LeaveRule_T__52();

	// $ANTLR start "T__52"
	[GrammarRule("T__52")]
	private void mT__52()
	{
		EnterRule_T__52();
		EnterRule("T__52", 12);
		TraceIn("T__52", 12);
		try
		{
			int _type = T__52;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:18:7: ( '#include' )
			DebugEnterAlt(1);
			// CCompiler.g:18:9: '#include'
			{
			DebugLocation(18, 9);
			Match("#include"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__52", 12);
			LeaveRule("T__52", 12);
			LeaveRule_T__52();
		}
	}
	// $ANTLR end "T__52"

	partial void EnterRule_T__53();
	partial void LeaveRule_T__53();

	// $ANTLR start "T__53"
	[GrammarRule("T__53")]
	private void mT__53()
	{
		EnterRule_T__53();
		EnterRule("T__53", 13);
		TraceIn("T__53", 13);
		try
		{
			int _type = T__53;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:19:7: ( '(' )
			DebugEnterAlt(1);
			// CCompiler.g:19:9: '('
			{
			DebugLocation(19, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__53", 13);
			LeaveRule("T__53", 13);
			LeaveRule_T__53();
		}
	}
	// $ANTLR end "T__53"

	partial void EnterRule_T__54();
	partial void LeaveRule_T__54();

	// $ANTLR start "T__54"
	[GrammarRule("T__54")]
	private void mT__54()
	{
		EnterRule_T__54();
		EnterRule("T__54", 14);
		TraceIn("T__54", 14);
		try
		{
			int _type = T__54;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:20:7: ( ')' )
			DebugEnterAlt(1);
			// CCompiler.g:20:9: ')'
			{
			DebugLocation(20, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__54", 14);
			LeaveRule("T__54", 14);
			LeaveRule_T__54();
		}
	}
	// $ANTLR end "T__54"

	partial void EnterRule_T__55();
	partial void LeaveRule_T__55();

	// $ANTLR start "T__55"
	[GrammarRule("T__55")]
	private void mT__55()
	{
		EnterRule_T__55();
		EnterRule("T__55", 15);
		TraceIn("T__55", 15);
		try
		{
			int _type = T__55;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:21:7: ( '[' )
			DebugEnterAlt(1);
			// CCompiler.g:21:9: '['
			{
			DebugLocation(21, 9);
			Match('['); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__55", 15);
			LeaveRule("T__55", 15);
			LeaveRule_T__55();
		}
	}
	// $ANTLR end "T__55"

	partial void EnterRule_T__56();
	partial void LeaveRule_T__56();

	// $ANTLR start "T__56"
	[GrammarRule("T__56")]
	private void mT__56()
	{
		EnterRule_T__56();
		EnterRule("T__56", 16);
		TraceIn("T__56", 16);
		try
		{
			int _type = T__56;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:22:7: ( ']' )
			DebugEnterAlt(1);
			// CCompiler.g:22:9: ']'
			{
			DebugLocation(22, 9);
			Match(']'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__56", 16);
			LeaveRule("T__56", 16);
			LeaveRule_T__56();
		}
	}
	// $ANTLR end "T__56"

	partial void EnterRule_T__57();
	partial void LeaveRule_T__57();

	// $ANTLR start "T__57"
	[GrammarRule("T__57")]
	private void mT__57()
	{
		EnterRule_T__57();
		EnterRule("T__57", 17);
		TraceIn("T__57", 17);
		try
		{
			int _type = T__57;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:23:7: ( '{' )
			DebugEnterAlt(1);
			// CCompiler.g:23:9: '{'
			{
			DebugLocation(23, 9);
			Match('{'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__57", 17);
			LeaveRule("T__57", 17);
			LeaveRule_T__57();
		}
	}
	// $ANTLR end "T__57"

	partial void EnterRule_T__58();
	partial void LeaveRule_T__58();

	// $ANTLR start "T__58"
	[GrammarRule("T__58")]
	private void mT__58()
	{
		EnterRule_T__58();
		EnterRule("T__58", 18);
		TraceIn("T__58", 18);
		try
		{
			int _type = T__58;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:24:7: ( '}' )
			DebugEnterAlt(1);
			// CCompiler.g:24:9: '}'
			{
			DebugLocation(24, 9);
			Match('}'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__58", 18);
			LeaveRule("T__58", 18);
			LeaveRule_T__58();
		}
	}
	// $ANTLR end "T__58"

	partial void EnterRule_NOT();
	partial void LeaveRule_NOT();

	// $ANTLR start "NOT"
	[GrammarRule("NOT")]
	private void mNOT()
	{
		EnterRule_NOT();
		EnterRule("NOT", 19);
		TraceIn("NOT", 19);
		try
		{
			int _type = NOT;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:36:4: ( '!' )
			DebugEnterAlt(1);
			// CCompiler.g:36:7: '!'
			{
			DebugLocation(36, 7);
			Match('!'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NOT", 19);
			LeaveRule("NOT", 19);
			LeaveRule_NOT();
		}
	}
	// $ANTLR end "NOT"

	partial void EnterRule_ADD();
	partial void LeaveRule_ADD();

	// $ANTLR start "ADD"
	[GrammarRule("ADD")]
	private void mADD()
	{
		EnterRule_ADD();
		EnterRule("ADD", 20);
		TraceIn("ADD", 20);
		try
		{
			int _type = ADD;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:37:4: ( '+' )
			DebugEnterAlt(1);
			// CCompiler.g:37:10: '+'
			{
			DebugLocation(37, 10);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ADD", 20);
			LeaveRule("ADD", 20);
			LeaveRule_ADD();
		}
	}
	// $ANTLR end "ADD"

	partial void EnterRule_SUB();
	partial void LeaveRule_SUB();

	// $ANTLR start "SUB"
	[GrammarRule("SUB")]
	private void mSUB()
	{
		EnterRule_SUB();
		EnterRule("SUB", 21);
		TraceIn("SUB", 21);
		try
		{
			int _type = SUB;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:38:4: ( '-' )
			DebugEnterAlt(1);
			// CCompiler.g:38:10: '-'
			{
			DebugLocation(38, 10);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("SUB", 21);
			LeaveRule("SUB", 21);
			LeaveRule_SUB();
		}
	}
	// $ANTLR end "SUB"

	partial void EnterRule_MUL();
	partial void LeaveRule_MUL();

	// $ANTLR start "MUL"
	[GrammarRule("MUL")]
	private void mMUL()
	{
		EnterRule_MUL();
		EnterRule("MUL", 22);
		TraceIn("MUL", 22);
		try
		{
			int _type = MUL;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:39:4: ( '*' )
			DebugEnterAlt(1);
			// CCompiler.g:39:10: '*'
			{
			DebugLocation(39, 10);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MUL", 22);
			LeaveRule("MUL", 22);
			LeaveRule_MUL();
		}
	}
	// $ANTLR end "MUL"

	partial void EnterRule_DIV();
	partial void LeaveRule_DIV();

	// $ANTLR start "DIV"
	[GrammarRule("DIV")]
	private void mDIV()
	{
		EnterRule_DIV();
		EnterRule("DIV", 23);
		TraceIn("DIV", 23);
		try
		{
			int _type = DIV;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:40:4: ( '/' )
			DebugEnterAlt(1);
			// CCompiler.g:40:10: '/'
			{
			DebugLocation(40, 10);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DIV", 23);
			LeaveRule("DIV", 23);
			LeaveRule_DIV();
		}
	}
	// $ANTLR end "DIV"

	partial void EnterRule_BIT_AND();
	partial void LeaveRule_BIT_AND();

	// $ANTLR start "BIT_AND"
	[GrammarRule("BIT_AND")]
	private void mBIT_AND()
	{
		EnterRule_BIT_AND();
		EnterRule("BIT_AND", 24);
		TraceIn("BIT_AND", 24);
		try
		{
			int _type = BIT_AND;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:41:8: ( '&' )
			DebugEnterAlt(1);
			// CCompiler.g:41:10: '&'
			{
			DebugLocation(41, 10);
			Match('&'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BIT_AND", 24);
			LeaveRule("BIT_AND", 24);
			LeaveRule_BIT_AND();
		}
	}
	// $ANTLR end "BIT_AND"

	partial void EnterRule_BIT_OR();
	partial void LeaveRule_BIT_OR();

	// $ANTLR start "BIT_OR"
	[GrammarRule("BIT_OR")]
	private void mBIT_OR()
	{
		EnterRule_BIT_OR();
		EnterRule("BIT_OR", 25);
		TraceIn("BIT_OR", 25);
		try
		{
			int _type = BIT_OR;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:42:7: ( '|' )
			DebugEnterAlt(1);
			// CCompiler.g:42:10: '|'
			{
			DebugLocation(42, 10);
			Match('|'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BIT_OR", 25);
			LeaveRule("BIT_OR", 25);
			LeaveRule_BIT_OR();
		}
	}
	// $ANTLR end "BIT_OR"

	partial void EnterRule_ASSIGN();
	partial void LeaveRule_ASSIGN();

	// $ANTLR start "ASSIGN"
	[GrammarRule("ASSIGN")]
	private void mASSIGN()
	{
		EnterRule_ASSIGN();
		EnterRule("ASSIGN", 26);
		TraceIn("ASSIGN", 26);
		try
		{
			int _type = ASSIGN;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:43:8: ( '=' | '*=' | '/=' | '%=' | '+=' | '-=' | '<<=' | '>>=' | '&=' | '^=' | '|=' )
			int alt1=11;
			try { DebugEnterDecision(1, false);
			switch (input.LA(1))
			{
			case '=':
				{
				alt1 = 1;
				}
				break;
			case '*':
				{
				alt1 = 2;
				}
				break;
			case '/':
				{
				alt1 = 3;
				}
				break;
			case '%':
				{
				alt1 = 4;
				}
				break;
			case '+':
				{
				alt1 = 5;
				}
				break;
			case '-':
				{
				alt1 = 6;
				}
				break;
			case '<':
				{
				alt1 = 7;
				}
				break;
			case '>':
				{
				alt1 = 8;
				}
				break;
			case '&':
				{
				alt1 = 9;
				}
				break;
			case '^':
				{
				alt1 = 10;
				}
				break;
			case '|':
				{
				alt1 = 11;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 1, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// CCompiler.g:43:10: '='
				{
				DebugLocation(43, 10);
				Match('='); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// CCompiler.g:44:4: '*='
				{
				DebugLocation(44, 4);
				Match("*="); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// CCompiler.g:45:4: '/='
				{
				DebugLocation(45, 4);
				Match("/="); 


				}
				break;
			case 4:
				DebugEnterAlt(4);
				// CCompiler.g:46:4: '%='
				{
				DebugLocation(46, 4);
				Match("%="); 


				}
				break;
			case 5:
				DebugEnterAlt(5);
				// CCompiler.g:47:4: '+='
				{
				DebugLocation(47, 4);
				Match("+="); 


				}
				break;
			case 6:
				DebugEnterAlt(6);
				// CCompiler.g:48:4: '-='
				{
				DebugLocation(48, 4);
				Match("-="); 


				}
				break;
			case 7:
				DebugEnterAlt(7);
				// CCompiler.g:49:4: '<<='
				{
				DebugLocation(49, 4);
				Match("<<="); 


				}
				break;
			case 8:
				DebugEnterAlt(8);
				// CCompiler.g:50:4: '>>='
				{
				DebugLocation(50, 4);
				Match(">>="); 


				}
				break;
			case 9:
				DebugEnterAlt(9);
				// CCompiler.g:51:4: '&='
				{
				DebugLocation(51, 4);
				Match("&="); 


				}
				break;
			case 10:
				DebugEnterAlt(10);
				// CCompiler.g:52:4: '^='
				{
				DebugLocation(52, 4);
				Match("^="); 


				}
				break;
			case 11:
				DebugEnterAlt(11);
				// CCompiler.g:53:4: '|='
				{
				DebugLocation(53, 4);
				Match("|="); 


				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ASSIGN", 26);
			LeaveRule("ASSIGN", 26);
			LeaveRule_ASSIGN();
		}
	}
	// $ANTLR end "ASSIGN"

	partial void EnterRule_GE();
	partial void LeaveRule_GE();

	// $ANTLR start "GE"
	[GrammarRule("GE")]
	private void mGE()
	{
		EnterRule_GE();
		EnterRule("GE", 27);
		TraceIn("GE", 27);
		try
		{
			int _type = GE;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:55:3: ( '>=' )
			DebugEnterAlt(1);
			// CCompiler.g:55:11: '>='
			{
			DebugLocation(55, 11);
			Match(">="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("GE", 27);
			LeaveRule("GE", 27);
			LeaveRule_GE();
		}
	}
	// $ANTLR end "GE"

	partial void EnterRule_LE();
	partial void LeaveRule_LE();

	// $ANTLR start "LE"
	[GrammarRule("LE")]
	private void mLE()
	{
		EnterRule_LE();
		EnterRule("LE", 28);
		TraceIn("LE", 28);
		try
		{
			int _type = LE;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:56:3: ( '<=' )
			DebugEnterAlt(1);
			// CCompiler.g:56:11: '<='
			{
			DebugLocation(56, 11);
			Match("<="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LE", 28);
			LeaveRule("LE", 28);
			LeaveRule_LE();
		}
	}
	// $ANTLR end "LE"

	partial void EnterRule_NE();
	partial void LeaveRule_NE();

	// $ANTLR start "NE"
	[GrammarRule("NE")]
	private void mNE()
	{
		EnterRule_NE();
		EnterRule("NE", 29);
		TraceIn("NE", 29);
		try
		{
			int _type = NE;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:57:3: ( '!=' )
			DebugEnterAlt(1);
			// CCompiler.g:57:6: '!='
			{
			DebugLocation(57, 6);
			Match("!="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NE", 29);
			LeaveRule("NE", 29);
			LeaveRule_NE();
		}
	}
	// $ANTLR end "NE"

	partial void EnterRule_EQ();
	partial void LeaveRule_EQ();

	// $ANTLR start "EQ"
	[GrammarRule("EQ")]
	private void mEQ()
	{
		EnterRule_EQ();
		EnterRule("EQ", 30);
		TraceIn("EQ", 30);
		try
		{
			int _type = EQ;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:58:3: ( '==' )
			DebugEnterAlt(1);
			// CCompiler.g:58:7: '=='
			{
			DebugLocation(58, 7);
			Match("=="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("EQ", 30);
			LeaveRule("EQ", 30);
			LeaveRule_EQ();
		}
	}
	// $ANTLR end "EQ"

	partial void EnterRule_GT();
	partial void LeaveRule_GT();

	// $ANTLR start "GT"
	[GrammarRule("GT")]
	private void mGT()
	{
		EnterRule_GT();
		EnterRule("GT", 31);
		TraceIn("GT", 31);
		try
		{
			int _type = GT;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:59:3: ( '>' )
			DebugEnterAlt(1);
			// CCompiler.g:59:11: '>'
			{
			DebugLocation(59, 11);
			Match('>'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("GT", 31);
			LeaveRule("GT", 31);
			LeaveRule_GT();
		}
	}
	// $ANTLR end "GT"

	partial void EnterRule_LT();
	partial void LeaveRule_LT();

	// $ANTLR start "LT"
	[GrammarRule("LT")]
	private void mLT()
	{
		EnterRule_LT();
		EnterRule("LT", 32);
		TraceIn("LT", 32);
		try
		{
			int _type = LT;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:60:3: ( '<' )
			DebugEnterAlt(1);
			// CCompiler.g:60:11: '<'
			{
			DebugLocation(60, 11);
			Match('<'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LT", 32);
			LeaveRule("LT", 32);
			LeaveRule_LT();
		}
	}
	// $ANTLR end "LT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 33);
		TraceIn("WS", 33);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:63:5: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
			DebugEnterAlt(1);
			// CCompiler.g:63:8: ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' )
			{
			DebugLocation(63, 8);
			if ((input.LA(1)>='\t' && input.LA(1)<='\n')||(input.LA(1)>='\f' && input.LA(1)<='\r')||input.LA(1)==' ')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(63, 38);
			_channel=Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 33);
			LeaveRule("WS", 33);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_ML_COMMENT();
	partial void LeaveRule_ML_COMMENT();

	// $ANTLR start "ML_COMMENT"
	[GrammarRule("ML_COMMENT")]
	private void mML_COMMENT()
	{
		EnterRule_ML_COMMENT();
		EnterRule("ML_COMMENT", 34);
		TraceIn("ML_COMMENT", 34);
		try
		{
			int _type = ML_COMMENT;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:67:11: ( '/*' ( options {greedy=false; } : . )* '*/' )
			DebugEnterAlt(1);
			// CCompiler.g:68:3: '/*' ( options {greedy=false; } : . )* '*/'
			{
			DebugLocation(68, 3);
			Match("/*"); 

			DebugLocation(68, 8);
			// CCompiler.g:68:8: ( options {greedy=false; } : . )*
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_0 = input.LA(1);

				if ((LA2_0=='*'))
				{
					int LA2_1 = input.LA(2);

					if ((LA2_1=='/'))
					{
						alt2 = 2;
					}
					else if (((LA2_1>='\u0000' && LA2_1<='.')||(LA2_1>='0' && LA2_1<='\uFFFF')))
					{
						alt2 = 1;
					}


				}
				else if (((LA2_0>='\u0000' && LA2_0<=')')||(LA2_0>='+' && LA2_0<='\uFFFF')))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch ( alt2 )
				{
				case 1:
					DebugEnterAlt(1);
					// CCompiler.g:68:38: .
					{
					DebugLocation(68, 38);
					MatchAny(); 

					}
					break;

				default:
					goto loop2;
				}
			}

			loop2:
				;

			} finally { DebugExitSubRule(2); }

			DebugLocation(68, 43);
			Match("*/"); 

			DebugLocation(68, 48);

			    _channel=Hidden;
			  

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ML_COMMENT", 34);
			LeaveRule("ML_COMMENT", 34);
			LeaveRule_ML_COMMENT();
		}
	}
	// $ANTLR end "ML_COMMENT"

	partial void EnterRule_LINE_COMMENT();
	partial void LeaveRule_LINE_COMMENT();

	// $ANTLR start "LINE_COMMENT"
	[GrammarRule("LINE_COMMENT")]
	private void mLINE_COMMENT()
	{
		EnterRule_LINE_COMMENT();
		EnterRule("LINE_COMMENT", 35);
		TraceIn("LINE_COMMENT", 35);
		try
		{
			int _type = LINE_COMMENT;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:74:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' )
			DebugEnterAlt(1);
			// CCompiler.g:74:7: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
			{
			DebugLocation(74, 7);
			Match("//"); 

			DebugLocation(74, 12);
			// CCompiler.g:74:12: (~ ( '\\n' | '\\r' ) )*
			try { DebugEnterSubRule(3);
			while (true)
			{
				int alt3=2;
				try { DebugEnterDecision(3, false);
				int LA3_0 = input.LA(1);

				if (((LA3_0>='\u0000' && LA3_0<='\t')||(LA3_0>='\u000B' && LA3_0<='\f')||(LA3_0>='\u000E' && LA3_0<='\uFFFF')))
				{
					alt3 = 1;
				}


				} finally { DebugExitDecision(3); }
				switch ( alt3 )
				{
				case 1:
					DebugEnterAlt(1);
					// CCompiler.g:
					{
					DebugLocation(74, 12);
					input.Consume();


					}
					break;

				default:
					goto loop3;
				}
			}

			loop3:
				;

			} finally { DebugExitSubRule(3); }

			DebugLocation(74, 26);
			// CCompiler.g:74:26: ( '\\r' )?
			int alt4=2;
			try { DebugEnterSubRule(4);
			try { DebugEnterDecision(4, false);
			int LA4_0 = input.LA(1);

			if ((LA4_0=='\r'))
			{
				alt4 = 1;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// CCompiler.g:74:26: '\\r'
				{
				DebugLocation(74, 26);
				Match('\r'); 

				}
				break;

			}
			} finally { DebugExitSubRule(4); }

			DebugLocation(74, 32);
			Match('\n'); 
			DebugLocation(74, 37);
			_channel=Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LINE_COMMENT", 35);
			LeaveRule("LINE_COMMENT", 35);
			LeaveRule_LINE_COMMENT();
		}
	}
	// $ANTLR end "LINE_COMMENT"

	partial void EnterRule_DIGIT();
	partial void LeaveRule_DIGIT();

	// $ANTLR start "DIGIT"
	[GrammarRule("DIGIT")]
	private void mDIGIT()
	{
		EnterRule_DIGIT();
		EnterRule("DIGIT", 36);
		TraceIn("DIGIT", 36);
		try
		{
			// CCompiler.g:77:15: ( '0' .. '9' )
			DebugEnterAlt(1);
			// CCompiler.g:
			{
			DebugLocation(77, 15);
			if ((input.LA(1)>='0' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("DIGIT", 36);
			LeaveRule("DIGIT", 36);
			LeaveRule_DIGIT();
		}
	}
	// $ANTLR end "DIGIT"

	partial void EnterRule_LETTER();
	partial void LeaveRule_LETTER();

	// $ANTLR start "LETTER"
	[GrammarRule("LETTER")]
	private void mLETTER()
	{
		EnterRule_LETTER();
		EnterRule("LETTER", 37);
		TraceIn("LETTER", 37);
		try
		{
			// CCompiler.g:81:16: ( 'a' .. 'z' | 'A' .. 'Z' | '_' )
			DebugEnterAlt(1);
			// CCompiler.g:
			{
			DebugLocation(81, 16);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("LETTER", 37);
			LeaveRule("LETTER", 37);
			LeaveRule_LETTER();
		}
	}
	// $ANTLR end "LETTER"

	partial void EnterRule_NUMBER();
	partial void LeaveRule_NUMBER();

	// $ANTLR start "NUMBER"
	[GrammarRule("NUMBER")]
	private void mNUMBER()
	{
		EnterRule_NUMBER();
		EnterRule("NUMBER", 38);
		TraceIn("NUMBER", 38);
		try
		{
			int _type = NUMBER;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:85:7: ( ( DIGIT )+ ( '.' ( DIGIT )+ )? )
			DebugEnterAlt(1);
			// CCompiler.g:86:3: ( DIGIT )+ ( '.' ( DIGIT )+ )?
			{
			DebugLocation(86, 3);
			// CCompiler.g:86:3: ( DIGIT )+
			int cnt5=0;
			try { DebugEnterSubRule(5);
			while (true)
			{
				int alt5=2;
				try { DebugEnterDecision(5, false);
				int LA5_0 = input.LA(1);

				if (((LA5_0>='0' && LA5_0<='9')))
				{
					alt5 = 1;
				}


				} finally { DebugExitDecision(5); }
				switch (alt5)
				{
				case 1:
					DebugEnterAlt(1);
					// CCompiler.g:
					{
					DebugLocation(86, 3);
					input.Consume();


					}
					break;

				default:
					if (cnt5 >= 1)
						goto loop5;

					EarlyExitException eee5 = new EarlyExitException( 5, input );
					DebugRecognitionException(eee5);
					throw eee5;
				}
				cnt5++;
			}
			loop5:
				;

			} finally { DebugExitSubRule(5); }

			DebugLocation(86, 10);
			// CCompiler.g:86:10: ( '.' ( DIGIT )+ )?
			int alt7=2;
			try { DebugEnterSubRule(7);
			try { DebugEnterDecision(7, false);
			int LA7_0 = input.LA(1);

			if ((LA7_0=='.'))
			{
				alt7 = 1;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// CCompiler.g:86:11: '.' ( DIGIT )+
				{
				DebugLocation(86, 11);
				Match('.'); 
				DebugLocation(86, 15);
				// CCompiler.g:86:15: ( DIGIT )+
				int cnt6=0;
				try { DebugEnterSubRule(6);
				while (true)
				{
					int alt6=2;
					try { DebugEnterDecision(6, false);
					int LA6_0 = input.LA(1);

					if (((LA6_0>='0' && LA6_0<='9')))
					{
						alt6 = 1;
					}


					} finally { DebugExitDecision(6); }
					switch (alt6)
					{
					case 1:
						DebugEnterAlt(1);
						// CCompiler.g:
						{
						DebugLocation(86, 15);
						input.Consume();


						}
						break;

					default:
						if (cnt6 >= 1)
							goto loop6;

						EarlyExitException eee6 = new EarlyExitException( 6, input );
						DebugRecognitionException(eee6);
						throw eee6;
					}
					cnt6++;
				}
				loop6:
					;

				} finally { DebugExitSubRule(6); }


				}
				break;

			}
			} finally { DebugExitSubRule(7); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NUMBER", 38);
			LeaveRule("NUMBER", 38);
			LeaveRule_NUMBER();
		}
	}
	// $ANTLR end "NUMBER"

	partial void EnterRule_EscapeSequence();
	partial void LeaveRule_EscapeSequence();

	// $ANTLR start "EscapeSequence"
	[GrammarRule("EscapeSequence")]
	private void mEscapeSequence()
	{
		EnterRule_EscapeSequence();
		EnterRule("EscapeSequence", 39);
		TraceIn("EscapeSequence", 39);
		try
		{
			// CCompiler.g:92:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) | OctalEscape )
			int alt8=2;
			try { DebugEnterDecision(8, false);
			int LA8_0 = input.LA(1);

			if ((LA8_0=='\\'))
			{
				int LA8_1 = input.LA(2);

				if ((LA8_1=='\"'||LA8_1=='\''||LA8_1=='\\'||LA8_1=='b'||LA8_1=='f'||LA8_1=='n'||LA8_1=='r'||LA8_1=='t'))
				{
					alt8 = 1;
				}
				else if (((LA8_1>='0' && LA8_1<='7')))
				{
					alt8 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 8, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 8, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(8); }
			switch (alt8)
			{
			case 1:
				DebugEnterAlt(1);
				// CCompiler.g:92:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
				{
				DebugLocation(92, 9);
				Match('\\'); 
				DebugLocation(92, 14);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// CCompiler.g:93:9: OctalEscape
				{
				DebugLocation(93, 9);
				mOctalEscape(); 

				}
				break;

			}
		}
		finally
		{
			TraceOut("EscapeSequence", 39);
			LeaveRule("EscapeSequence", 39);
			LeaveRule_EscapeSequence();
		}
	}
	// $ANTLR end "EscapeSequence"

	partial void EnterRule_OctalEscape();
	partial void LeaveRule_OctalEscape();

	// $ANTLR start "OctalEscape"
	[GrammarRule("OctalEscape")]
	private void mOctalEscape()
	{
		EnterRule_OctalEscape();
		EnterRule("OctalEscape", 40);
		TraceIn("OctalEscape", 40);
		try
		{
			// CCompiler.g:98:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )
			int alt9=3;
			try { DebugEnterDecision(9, false);
			int LA9_0 = input.LA(1);

			if ((LA9_0=='\\'))
			{
				int LA9_1 = input.LA(2);

				if (((LA9_1>='0' && LA9_1<='3')))
				{
					int LA9_2 = input.LA(3);

					if (((LA9_2>='0' && LA9_2<='7')))
					{
						int LA9_4 = input.LA(4);

						if (((LA9_4>='0' && LA9_4<='7')))
						{
							alt9 = 1;
						}
						else
						{
							alt9 = 2;
						}
					}
					else
					{
						alt9 = 3;
					}
				}
				else if (((LA9_1>='4' && LA9_1<='7')))
				{
					int LA9_3 = input.LA(3);

					if (((LA9_3>='0' && LA9_3<='7')))
					{
						alt9 = 2;
					}
					else
					{
						alt9 = 3;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 9, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 9, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// CCompiler.g:98:9: '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(98, 9);
				Match('\\'); 
				DebugLocation(98, 14);
				input.Consume();

				DebugLocation(98, 25);
				input.Consume();

				DebugLocation(98, 36);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// CCompiler.g:99:9: '\\\\' ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(99, 9);
				Match('\\'); 
				DebugLocation(99, 14);
				input.Consume();

				DebugLocation(99, 25);
				input.Consume();


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// CCompiler.g:100:9: '\\\\' ( '0' .. '7' )
				{
				DebugLocation(100, 9);
				Match('\\'); 
				DebugLocation(100, 14);
				input.Consume();


				}
				break;

			}
		}
		finally
		{
			TraceOut("OctalEscape", 40);
			LeaveRule("OctalEscape", 40);
			LeaveRule_OctalEscape();
		}
	}
	// $ANTLR end "OctalEscape"

	partial void EnterRule_STRING();
	partial void LeaveRule_STRING();

	// $ANTLR start "STRING"
	[GrammarRule("STRING")]
	private void mSTRING()
	{
		EnterRule_STRING();
		EnterRule("STRING", 41);
		TraceIn("STRING", 41);
		try
		{
			int _type = STRING;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:103:7: ( '\"' ( EscapeSequence |~ ( '\\\\' | '\"' ) )* '\"' )
			DebugEnterAlt(1);
			// CCompiler.g:104:3: '\"' ( EscapeSequence |~ ( '\\\\' | '\"' ) )* '\"'
			{
			DebugLocation(104, 3);
			Match('\"'); 
			DebugLocation(104, 7);
			// CCompiler.g:104:7: ( EscapeSequence |~ ( '\\\\' | '\"' ) )*
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=3;
				try { DebugEnterDecision(10, false);
				int LA10_0 = input.LA(1);

				if ((LA10_0=='\\'))
				{
					alt10 = 1;
				}
				else if (((LA10_0>='\u0000' && LA10_0<='!')||(LA10_0>='#' && LA10_0<='[')||(LA10_0>=']' && LA10_0<='\uFFFF')))
				{
					alt10 = 2;
				}


				} finally { DebugExitDecision(10); }
				switch ( alt10 )
				{
				case 1:
					DebugEnterAlt(1);
					// CCompiler.g:104:9: EscapeSequence
					{
					DebugLocation(104, 9);
					mEscapeSequence(); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// CCompiler.g:104:26: ~ ( '\\\\' | '\"' )
					{
					DebugLocation(104, 26);
					input.Consume();


					}
					break;

				default:
					goto loop10;
				}
			}

			loop10:
				;

			} finally { DebugExitSubRule(10); }

			DebugLocation(104, 41);
			Match('\"'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING", 41);
			LeaveRule("STRING", 41);
			LeaveRule_STRING();
		}
	}
	// $ANTLR end "STRING"

	partial void EnterRule_INCLUDE_STRING();
	partial void LeaveRule_INCLUDE_STRING();

	// $ANTLR start "INCLUDE_STRING"
	[GrammarRule("INCLUDE_STRING")]
	private void mINCLUDE_STRING()
	{
		EnterRule_INCLUDE_STRING();
		EnterRule("INCLUDE_STRING", 42);
		TraceIn("INCLUDE_STRING", 42);
		try
		{
			int _type = INCLUDE_STRING;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:107:15: ( '<' (~ '>' )* '>' )
			DebugEnterAlt(1);
			// CCompiler.g:108:3: '<' (~ '>' )* '>'
			{
			DebugLocation(108, 3);
			Match('<'); 
			DebugLocation(108, 7);
			// CCompiler.g:108:7: (~ '>' )*
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=2;
				try { DebugEnterDecision(11, false);
				int LA11_0 = input.LA(1);

				if (((LA11_0>='\u0000' && LA11_0<='=')||(LA11_0>='?' && LA11_0<='\uFFFF')))
				{
					alt11 = 1;
				}


				} finally { DebugExitDecision(11); }
				switch ( alt11 )
				{
				case 1:
					DebugEnterAlt(1);
					// CCompiler.g:
					{
					DebugLocation(108, 7);
					input.Consume();


					}
					break;

				default:
					goto loop11;
				}
			}

			loop11:
				;

			} finally { DebugExitSubRule(11); }

			DebugLocation(108, 13);
			Match('>'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INCLUDE_STRING", 42);
			LeaveRule("INCLUDE_STRING", 42);
			LeaveRule_INCLUDE_STRING();
		}
	}
	// $ANTLR end "INCLUDE_STRING"

	partial void EnterRule_SEMI();
	partial void LeaveRule_SEMI();

	// $ANTLR start "SEMI"
	[GrammarRule("SEMI")]
	private void mSEMI()
	{
		EnterRule_SEMI();
		EnterRule("SEMI", 43);
		TraceIn("SEMI", 43);
		try
		{
			int _type = SEMI;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:111:5: ( ';' )
			DebugEnterAlt(1);
			// CCompiler.g:111:7: ';'
			{
			DebugLocation(111, 7);
			Match(';'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("SEMI", 43);
			LeaveRule("SEMI", 43);
			LeaveRule_SEMI();
		}
	}
	// $ANTLR end "SEMI"

	partial void EnterRule_COMMA();
	partial void LeaveRule_COMMA();

	// $ANTLR start "COMMA"
	[GrammarRule("COMMA")]
	private void mCOMMA()
	{
		EnterRule_COMMA();
		EnterRule("COMMA", 44);
		TraceIn("COMMA", 44);
		try
		{
			int _type = COMMA;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:112:6: ( ',' )
			DebugEnterAlt(1);
			// CCompiler.g:112:8: ','
			{
			DebugLocation(112, 8);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMA", 44);
			LeaveRule("COMMA", 44);
			LeaveRule_COMMA();
		}
	}
	// $ANTLR end "COMMA"

	partial void EnterRule_IDENT();
	partial void LeaveRule_IDENT();

	// $ANTLR start "IDENT"
	[GrammarRule("IDENT")]
	private void mIDENT()
	{
		EnterRule_IDENT();
		EnterRule("IDENT", 45);
		TraceIn("IDENT", 45);
		try
		{
			int _type = IDENT;
			int _channel = DefaultTokenChannel;
			// CCompiler.g:115:6: ( LETTER ( LETTER | DIGIT )* )
			DebugEnterAlt(1);
			// CCompiler.g:116:3: LETTER ( LETTER | DIGIT )*
			{
			DebugLocation(116, 3);
			mLETTER(); 
			DebugLocation(116, 10);
			// CCompiler.g:116:10: ( LETTER | DIGIT )*
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=2;
				try { DebugEnterDecision(12, false);
				int LA12_0 = input.LA(1);

				if (((LA12_0>='0' && LA12_0<='9')||(LA12_0>='A' && LA12_0<='Z')||LA12_0=='_'||(LA12_0>='a' && LA12_0<='z')))
				{
					alt12 = 1;
				}


				} finally { DebugExitDecision(12); }
				switch ( alt12 )
				{
				case 1:
					DebugEnterAlt(1);
					// CCompiler.g:
					{
					DebugLocation(116, 10);
					input.Consume();


					}
					break;

				default:
					goto loop12;
				}
			}

			loop12:
				;

			} finally { DebugExitSubRule(12); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("IDENT", 45);
			LeaveRule("IDENT", 45);
			LeaveRule_IDENT();
		}
	}
	// $ANTLR end "IDENT"

	public override void mTokens()
	{
		// CCompiler.g:1:8: ( AND | DO | ELSE | FALSE | FOR | IF | OR | RETURN | TRUE | VAR | WHILE | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | NOT | ADD | SUB | MUL | DIV | BIT_AND | BIT_OR | ASSIGN | GE | LE | NE | EQ | GT | LT | WS | ML_COMMENT | LINE_COMMENT | NUMBER | STRING | INCLUDE_STRING | SEMI | COMMA | IDENT )
		int alt13=41;
		try { DebugEnterDecision(13, false);
		try
		{
			alt13 = dfa13.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(13); }
		switch (alt13)
		{
		case 1:
			DebugEnterAlt(1);
			// CCompiler.g:1:10: AND
			{
			DebugLocation(1, 10);
			mAND(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// CCompiler.g:1:14: DO
			{
			DebugLocation(1, 14);
			mDO(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// CCompiler.g:1:17: ELSE
			{
			DebugLocation(1, 17);
			mELSE(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// CCompiler.g:1:22: FALSE
			{
			DebugLocation(1, 22);
			mFALSE(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// CCompiler.g:1:28: FOR
			{
			DebugLocation(1, 28);
			mFOR(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// CCompiler.g:1:32: IF
			{
			DebugLocation(1, 32);
			mIF(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// CCompiler.g:1:35: OR
			{
			DebugLocation(1, 35);
			mOR(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// CCompiler.g:1:38: RETURN
			{
			DebugLocation(1, 38);
			mRETURN(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// CCompiler.g:1:45: TRUE
			{
			DebugLocation(1, 45);
			mTRUE(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// CCompiler.g:1:50: VAR
			{
			DebugLocation(1, 50);
			mVAR(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// CCompiler.g:1:54: WHILE
			{
			DebugLocation(1, 54);
			mWHILE(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// CCompiler.g:1:60: T__52
			{
			DebugLocation(1, 60);
			mT__52(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// CCompiler.g:1:66: T__53
			{
			DebugLocation(1, 66);
			mT__53(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// CCompiler.g:1:72: T__54
			{
			DebugLocation(1, 72);
			mT__54(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// CCompiler.g:1:78: T__55
			{
			DebugLocation(1, 78);
			mT__55(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// CCompiler.g:1:84: T__56
			{
			DebugLocation(1, 84);
			mT__56(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// CCompiler.g:1:90: T__57
			{
			DebugLocation(1, 90);
			mT__57(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// CCompiler.g:1:96: T__58
			{
			DebugLocation(1, 96);
			mT__58(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// CCompiler.g:1:102: NOT
			{
			DebugLocation(1, 102);
			mNOT(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// CCompiler.g:1:106: ADD
			{
			DebugLocation(1, 106);
			mADD(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// CCompiler.g:1:110: SUB
			{
			DebugLocation(1, 110);
			mSUB(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// CCompiler.g:1:114: MUL
			{
			DebugLocation(1, 114);
			mMUL(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// CCompiler.g:1:118: DIV
			{
			DebugLocation(1, 118);
			mDIV(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// CCompiler.g:1:122: BIT_AND
			{
			DebugLocation(1, 122);
			mBIT_AND(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// CCompiler.g:1:130: BIT_OR
			{
			DebugLocation(1, 130);
			mBIT_OR(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// CCompiler.g:1:137: ASSIGN
			{
			DebugLocation(1, 137);
			mASSIGN(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// CCompiler.g:1:144: GE
			{
			DebugLocation(1, 144);
			mGE(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// CCompiler.g:1:147: LE
			{
			DebugLocation(1, 147);
			mLE(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// CCompiler.g:1:150: NE
			{
			DebugLocation(1, 150);
			mNE(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// CCompiler.g:1:153: EQ
			{
			DebugLocation(1, 153);
			mEQ(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// CCompiler.g:1:156: GT
			{
			DebugLocation(1, 156);
			mGT(); 

			}
			break;
		case 32:
			DebugEnterAlt(32);
			// CCompiler.g:1:159: LT
			{
			DebugLocation(1, 159);
			mLT(); 

			}
			break;
		case 33:
			DebugEnterAlt(33);
			// CCompiler.g:1:162: WS
			{
			DebugLocation(1, 162);
			mWS(); 

			}
			break;
		case 34:
			DebugEnterAlt(34);
			// CCompiler.g:1:165: ML_COMMENT
			{
			DebugLocation(1, 165);
			mML_COMMENT(); 

			}
			break;
		case 35:
			DebugEnterAlt(35);
			// CCompiler.g:1:176: LINE_COMMENT
			{
			DebugLocation(1, 176);
			mLINE_COMMENT(); 

			}
			break;
		case 36:
			DebugEnterAlt(36);
			// CCompiler.g:1:189: NUMBER
			{
			DebugLocation(1, 189);
			mNUMBER(); 

			}
			break;
		case 37:
			DebugEnterAlt(37);
			// CCompiler.g:1:196: STRING
			{
			DebugLocation(1, 196);
			mSTRING(); 

			}
			break;
		case 38:
			DebugEnterAlt(38);
			// CCompiler.g:1:203: INCLUDE_STRING
			{
			DebugLocation(1, 203);
			mINCLUDE_STRING(); 

			}
			break;
		case 39:
			DebugEnterAlt(39);
			// CCompiler.g:1:218: SEMI
			{
			DebugLocation(1, 218);
			mSEMI(); 

			}
			break;
		case 40:
			DebugEnterAlt(40);
			// CCompiler.g:1:223: COMMA
			{
			DebugLocation(1, 223);
			mCOMMA(); 

			}
			break;
		case 41:
			DebugEnterAlt(41);
			// CCompiler.g:1:229: IDENT
			{
			DebugLocation(1, 229);
			mIDENT(); 

			}
			break;

		}

	}


	#region DFA
	DFA13 dfa13;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa13 = new DFA13(this, SpecialStateTransition13);
	}

	private class DFA13 : DFA
	{
		private const string DFA13_eotS =
			"\x1\xFFFF\x1\x22\x4\x20\x1\x29\x4\x20\x7\xFFFF\x1\x2F\x1\x30\x1\x31\x1"+
			"\x32\x1\x35\x1\x18\x1\xFFFF\x1\x39\x1\x3C\x8\xFFFF\x1\x3D\x3\x20\x1\x41"+
			"\x2\xFFFF\x4\x20\xA\xFFFF\x1\x47\x5\xFFFF\x2\x20\x1\x4A\x1\xFFFF\x2\x20"+
			"\x1\x4D\x1\x20\x1\x18\x1\xFFFF\x1\x4F\x1\x20\x1\xFFFF\x1\x20\x1\x52\x1"+
			"\xFFFF\x1\x20\x1\xFFFF\x1\x54\x1\x20\x1\xFFFF\x1\x56\x1\xFFFF\x1\x57"+
			"\x2\xFFFF";
		private const string DFA13_eofS =
			"\x58\xFFFF";
		private const string DFA13_minS =
			"\x1\x9\x1\x26\x1\x6F\x1\x6C\x1\x61\x1\x66\x1\x3D\x1\x65\x1\x72\x1\x61"+
			"\x1\x68\x7\xFFFF\x4\x3D\x1\x2A\x1\x3D\x1\xFFFF\x1\x0\x1\x3D\x8\xFFFF"+
			"\x1\x30\x1\x73\x1\x6C\x1\x72\x1\x30\x2\xFFFF\x1\x74\x1\x75\x1\x72\x1"+
			"\x69\x9\xFFFF\x2\x0\x5\xFFFF\x1\x65\x1\x73\x1\x30\x1\xFFFF\x1\x75\x1"+
			"\x65\x1\x30\x1\x6C\x1\x0\x1\xFFFF\x1\x30\x1\x65\x1\xFFFF\x1\x72\x1\x30"+
			"\x1\xFFFF\x1\x65\x1\xFFFF\x1\x30\x1\x6E\x1\xFFFF\x1\x30\x1\xFFFF\x1\x30"+
			"\x2\xFFFF";
		private const string DFA13_maxS =
			"\x1\x7D\x1\x3D\x1\x6F\x1\x6C\x1\x6F\x1\x66\x1\x7C\x1\x65\x1\x72\x1\x61"+
			"\x1\x68\x7\xFFFF\x6\x3D\x1\xFFFF\x1\xFFFF\x1\x3E\x8\xFFFF\x1\x7A\x1\x73"+
			"\x1\x6C\x1\x72\x1\x7A\x2\xFFFF\x1\x74\x1\x75\x1\x72\x1\x69\x9\xFFFF\x2"+
			"\xFFFF\x5\xFFFF\x1\x65\x1\x73\x1\x7A\x1\xFFFF\x1\x75\x1\x65\x1\x7A\x1"+
			"\x6C\x1\xFFFF\x1\xFFFF\x1\x7A\x1\x65\x1\xFFFF\x1\x72\x1\x7A\x1\xFFFF"+
			"\x1\x65\x1\xFFFF\x1\x7A\x1\x6E\x1\xFFFF\x1\x7A\x1\xFFFF\x1\x7A\x2\xFFFF";
		private const string DFA13_acceptS =
			"\xB\xFFFF\x1\xC\x1\xD\x1\xE\x1\xF\x1\x10\x1\x11\x1\x12\x6\xFFFF\x1\x1A"+
			"\x2\xFFFF\x1\x21\x1\x24\x1\x25\x1\x27\x1\x28\x1\x29\x1\x1\x1\x18\x5\xFFFF"+
			"\x1\x7\x1\x19\x4\xFFFF\x1\x1D\x1\x13\x1\x14\x1\x15\x1\x16\x1\x22\x1\x23"+
			"\x1\x17\x1\x1E\x2\xFFFF\x1\x20\x1\x26\x1\x1B\x1\x1F\x1\x2\x3\xFFFF\x1"+
			"\x6\x5\xFFFF\x1\x1C\x2\xFFFF\x1\x5\x2\xFFFF\x1\xA\x1\xFFFF\x1\x3\x2\xFFFF"+
			"\x1\x9\x1\xFFFF\x1\x4\x1\xFFFF\x1\xB\x1\x8";
		private const string DFA13_specialS =
			"\x19\xFFFF\x1\x1\x1D\xFFFF\x1\x3\x1\x0\xD\xFFFF\x1\x2\x11\xFFFF}>";
		private static readonly string[] DFA13_transitionS =
			{
				"\x2\x1B\x1\xFFFF\x2\x1B\x12\xFFFF\x1\x1B\x1\x12\x1\x1D\x1\xB\x1\xFFFF"+
				"\x1\x18\x1\x1\x1\xFFFF\x1\xC\x1\xD\x1\x15\x1\x13\x1\x1F\x1\x14\x1\xFFFF"+
				"\x1\x16\xA\x1C\x1\xFFFF\x1\x1E\x1\x19\x1\x17\x1\x1A\x2\xFFFF\x1A\x20"+
				"\x1\xE\x1\xFFFF\x1\xF\x1\x18\x1\x20\x1\xFFFF\x3\x20\x1\x2\x1\x3\x1\x4"+
				"\x2\x20\x1\x5\x8\x20\x1\x7\x1\x20\x1\x8\x1\x20\x1\x9\x1\xA\x3\x20\x1"+
				"\x10\x1\x6\x1\x11",
				"\x1\x21\x16\xFFFF\x1\x18",
				"\x1\x23",
				"\x1\x24",
				"\x1\x25\xD\xFFFF\x1\x26",
				"\x1\x27",
				"\x1\x18\x3E\xFFFF\x1\x28",
				"\x1\x2A",
				"\x1\x2B",
				"\x1\x2C",
				"\x1\x2D",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x2E",
				"\x1\x18",
				"\x1\x18",
				"\x1\x18",
				"\x1\x33\x4\xFFFF\x1\x34\xD\xFFFF\x1\x18",
				"\x1\x36",
				"",
				"\x3C\x3A\x1\x37\x1\x38\xFFC2\x3A",
				"\x1\x3B\x1\x18",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"\x1\x3E",
				"\x1\x3F",
				"\x1\x40",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"",
				"",
				"\x1\x42",
				"\x1\x43",
				"\x1\x44",
				"\x1\x45",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x3D\x3A\x1\x46\xFFC2\x3A",
				"\x0\x3A",
				"",
				"",
				"",
				"",
				"",
				"\x1\x48",
				"\x1\x49",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"",
				"\x1\x4B",
				"\x1\x4C",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"\x1\x4E",
				"\x0\x3A",
				"",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"\x1\x50",
				"",
				"\x1\x51",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"",
				"\x1\x53",
				"",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"\x1\x55",
				"",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"",
				"\xA\x20\x7\xFFFF\x1A\x20\x4\xFFFF\x1\x20\x1\xFFFF\x1A\x20",
				"",
				""
			};

		private static readonly short[] DFA13_eot = DFA.UnpackEncodedString(DFA13_eotS);
		private static readonly short[] DFA13_eof = DFA.UnpackEncodedString(DFA13_eofS);
		private static readonly char[] DFA13_min = DFA.UnpackEncodedStringToUnsignedChars(DFA13_minS);
		private static readonly char[] DFA13_max = DFA.UnpackEncodedStringToUnsignedChars(DFA13_maxS);
		private static readonly short[] DFA13_accept = DFA.UnpackEncodedString(DFA13_acceptS);
		private static readonly short[] DFA13_special = DFA.UnpackEncodedString(DFA13_specialS);
		private static readonly short[][] DFA13_transition;

		static DFA13()
		{
			int numStates = DFA13_transitionS.Length;
			DFA13_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA13_transition[i] = DFA.UnpackEncodedString(DFA13_transitionS[i]);
			}
		}

		public DFA13( BaseRecognizer recognizer, SpecialStateTransitionHandler specialStateTransition )
			: base(specialStateTransition)
		{
			this.recognizer = recognizer;
			this.decisionNumber = 13;
			this.eot = DFA13_eot;
			this.eof = DFA13_eof;
			this.min = DFA13_min;
			this.max = DFA13_max;
			this.accept = DFA13_accept;
			this.special = DFA13_special;
			this.transition = DFA13_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( AND | DO | ELSE | FALSE | FOR | IF | OR | RETURN | TRUE | VAR | WHILE | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | NOT | ADD | SUB | MUL | DIV | BIT_AND | BIT_OR | ASSIGN | GE | LE | NE | EQ | GT | LT | WS | ML_COMMENT | LINE_COMMENT | NUMBER | STRING | INCLUDE_STRING | SEMI | COMMA | IDENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private int SpecialStateTransition13(DFA dfa, int s, IIntStream _input)
	{
		IIntStream input = _input;
		int _s = s;
		switch (s)
		{
			case 0:
				int LA13_56 = input.LA(1);

				s = -1;
				if (((LA13_56>='\u0000' && LA13_56<='\uFFFF'))) {s = 58;}

				else s = 71;

				if (s >= 0) return s;
				break;

			case 1:
				int LA13_25 = input.LA(1);

				s = -1;
				if ((LA13_25=='<')) {s = 55;}

				else if ((LA13_25=='=')) {s = 56;}

				else if (((LA13_25>='\u0000' && LA13_25<=';')||(LA13_25>='>' && LA13_25<='\uFFFF'))) {s = 58;}

				else s = 57;

				if (s >= 0) return s;
				break;

			case 2:
				int LA13_70 = input.LA(1);

				s = -1;
				if (((LA13_70>='\u0000' && LA13_70<='\uFFFF'))) {s = 58;}

				else s = 24;

				if (s >= 0) return s;
				break;

			case 3:
				int LA13_55 = input.LA(1);

				s = -1;
				if ((LA13_55=='=')) {s = 70;}

				else if (((LA13_55>='\u0000' && LA13_55<='<')||(LA13_55>='>' && LA13_55<='\uFFFF'))) {s = 58;}

				if (s >= 0) return s;
				break;
		}
		NoViableAltException nvae = new NoViableAltException(dfa.Description, 13, _s, input);
		dfa.Error(nvae);
		throw nvae;
	}
 
	#endregion

}
